[package]
authors = ["Lukas Kalbertodt <lukas.kalbertodt@gmail.com>"]
license = "MIT/Apache-2.0"
name = "base"
publish = false
version = "0.1.0"

[dependencies]
cgmath = "0.10.0"
num-traits = "0.1.33"
